### ISSUE TITLE
Issue with Item Tooltips

### ISSUE THREAD

**Issue by shoooobie** [LizzyMaybeDev/Patcher-Explanation#24]
Item Tooltips are not moved to above potion effects. 

This can be seen below.
![image](https://user-images.githubusercontent.com/29315025/132419442-dc6b02cc-5a1a-4eb5-9d3c-8df6e725f085.png)

This is in a Vanilla, singleplayer world, but it also doesn't work on any servers I have tried it on.

I also apologize in advance if this isn't the best place to submit an issue.

**Comment by LizzyMaybeDev** [comment]
you're right about it not being the best place as im not a part of the sk1er staff team anymore, if this still persists then put it in https://github.com/Sk1erLLC/Patcher/ since its now open source, cheers!
